server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fastgpt
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-3.5-turbo
      temperature: 0.7

logging:
  level:
    root: INFO
    com.fastgpt: DEBUG 